# This is a basic workflow to help you get started with Actions
name: Simple Manual Workflow - Three Env

# Controls when the action will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - uses: actions/checkout@v4
      - name: Run a script
        run: |
          echo "I am running a job in the DEV environment"

  QA:
    runs-on: ubuntu-latest
    environment: Staging
    needs: DEV

    steps:
      - uses: actions/checkout@v4
      - name: Run a script
        run: |
          echo "I am running a job in the QA environment"

  PROD:
    runs-on: ubuntu-latest
    environment: Production
    needs: QA

    steps:
      - uses: actions/checkout@v4
      - name: Run a script
        run: |
          echo "I am running a job in the PROD environment"
